# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudAluno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=30)),
                ('ultimo_nome', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('idade', models.IntegerField()),
                ('genero', models.CharField(max_length=100)),
                ('periodo', models.IntegerField()),
                ('cra', models.DecimalField(decimal_places=2, max_digits=4)),
                ('curso', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Estudante',
        ),
    ]
