# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudAluno', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.AddField(
            model_name='aluno',
            name='curso',
            field=models.CharField(default='a', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='is_aluno',
            field=models.BooleanField(default=False),
        ),
    ]
