# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudAluno', '0002_auto_20160315_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='pessoa',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='is_aluno',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cra',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='curso',
            field=models.CharField(default='c', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='periodo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Aluno',
        ),
    ]
